Update borgbackup-1.2.4.tar.gz to 1.4.0
flathub/com.borgbase.Vorta pull request #168
Opened 2024-07-14 11:17 UTC by shivansh02

2024-07-14 11:22 UTC, shivansh02 commented
@Hofer-Julian Please take a look!

2024-07-14 13:12 UTC, Hofer-Julian commented
Hey @shivansh02, as far as I can tell https://github.com/borgbase/vorta/issues/1794 is not yet resolved. As far as I can tell, without a migration procedure some user would see their backups failing after we would upgrade borg. Or is this handled nowadays?

2024-07-14 18:19 UTC, m3nu commented
We won't implement https://github.com/borgbase/vorta/issues/1794, since too many things can go wrong to automate it within Vorta. And it seems to affect very few repos. I've seen virtually no questions or reports from users or my own repos.

2024-07-14 19:25 UTC, Hofer-Julian requested changes

2024-07-14 19:25 UTC, Hofer-Julian commented on dependencies/borgbackup.json
>                  }
This is not needed anymore

2024-07-14 19:26 UTC, Hofer-Julian commented
> I've seen virtually no questions or reports from users or my own repos.

If that's the case then I think there's no need to block here.

2024-07-15 12:10 UTC, Hofer-Julian approved these changes

2024-07-15 12:11 UTC, Hofer-Julian commented
Thanks @shivansh02!

2024-07-15 12:11 UTC, merged

2024-07-15 13:12 UTC, m3nu commented
Thank to the both of you!